# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/odyce/Epitech_Projects/R-Type/B-CPP-500-LIL-5-1-rtype-maximilien.vanstaevel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/odyce/Epitech_Projects/R-Type/B-CPP-500-LIL-5-1-rtype-maximilien.vanstaevel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cpack --config ./CPackSourceConfig.cmake /home/odyce/Epitech_Projects/R-Type/B-CPP-500-LIL-5-1-rtype-maximilien.vanstaevel/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/odyce/Downloads/clion-2021.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odyce/Epitech_Projects/R-Type/B-CPP-500-LIL-5-1-rtype-maximilien.vanstaevel/CMakeFiles /home/odyce/Epitech_Projects/R-Type/B-CPP-500-LIL-5-1-rtype-maximilien.vanstaevel//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/odyce/Epitech_Projects/R-Type/B-CPP-500-LIL-5-1-rtype-maximilien.vanstaevel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rtype-client

# Build rule for target.
rtype-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype-client
.PHONY : rtype-client

# fast build rule for target.
rtype-client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/build
.PHONY : rtype-client/fast

#=============================================================================
# Target rules for targets named rtype-server

# Build rule for target.
rtype-server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtype-server
.PHONY : rtype-server

# fast build rule for target.
rtype-server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/build
.PHONY : rtype-server/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f SFML/src/SFML/System/CMakeFiles/sfml-system.dir/build.make SFML/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f SFML/src/SFML/Window/CMakeFiles/sfml-window.dir/build.make SFML/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f SFML/src/SFML/Network/CMakeFiles/sfml-network.dir/build.make SFML/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f SFML/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make SFML/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) $(MAKESILENT) -f SFML/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build.make SFML/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

src/Entity/Entity.o: src/Entity/Entity.cpp.o
.PHONY : src/Entity/Entity.o

# target to build an object file
src/Entity/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/Entity/Entity.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/Entity/Entity.cpp.o
.PHONY : src/Entity/Entity.cpp.o

src/Entity/Entity.i: src/Entity/Entity.cpp.i
.PHONY : src/Entity/Entity.i

# target to preprocess a source file
src/Entity/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/Entity/Entity.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/Entity/Entity.cpp.i
.PHONY : src/Entity/Entity.cpp.i

src/Entity/Entity.s: src/Entity/Entity.cpp.s
.PHONY : src/Entity/Entity.s

# target to generate assembly for a file
src/Entity/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/Entity/Entity.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/Entity/Entity.cpp.s
.PHONY : src/Entity/Entity.cpp.s

src/Game/DevLevel.o: src/Game/DevLevel.cpp.o
.PHONY : src/Game/DevLevel.o

# target to build an object file
src/Game/DevLevel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/Game/DevLevel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/Game/DevLevel.cpp.o
.PHONY : src/Game/DevLevel.cpp.o

src/Game/DevLevel.i: src/Game/DevLevel.cpp.i
.PHONY : src/Game/DevLevel.i

# target to preprocess a source file
src/Game/DevLevel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/Game/DevLevel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/Game/DevLevel.cpp.i
.PHONY : src/Game/DevLevel.cpp.i

src/Game/DevLevel.s: src/Game/DevLevel.cpp.s
.PHONY : src/Game/DevLevel.s

# target to generate assembly for a file
src/Game/DevLevel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/Game/DevLevel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/Game/DevLevel.cpp.s
.PHONY : src/Game/DevLevel.cpp.s

src/System/System.o: src/System/System.cpp.o
.PHONY : src/System/System.o

# target to build an object file
src/System/System.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/System/System.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/System/System.cpp.o
.PHONY : src/System/System.cpp.o

src/System/System.i: src/System/System.cpp.i
.PHONY : src/System/System.i

# target to preprocess a source file
src/System/System.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/System/System.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/System/System.cpp.i
.PHONY : src/System/System.cpp.i

src/System/System.s: src/System/System.cpp.s
.PHONY : src/System/System.s

# target to generate assembly for a file
src/System/System.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/System/System.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/System/System.cpp.s
.PHONY : src/System/System.cpp.s

src/System/TestSystem.o: src/System/TestSystem.cpp.o
.PHONY : src/System/TestSystem.o

# target to build an object file
src/System/TestSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/System/TestSystem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/System/TestSystem.cpp.o
.PHONY : src/System/TestSystem.cpp.o

src/System/TestSystem.i: src/System/TestSystem.cpp.i
.PHONY : src/System/TestSystem.i

# target to preprocess a source file
src/System/TestSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/System/TestSystem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/System/TestSystem.cpp.i
.PHONY : src/System/TestSystem.cpp.i

src/System/TestSystem.s: src/System/TestSystem.cpp.s
.PHONY : src/System/TestSystem.s

# target to generate assembly for a file
src/System/TestSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/System/TestSystem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/System/TestSystem.cpp.s
.PHONY : src/System/TestSystem.cpp.s

src/World/World.o: src/World/World.cpp.o
.PHONY : src/World/World.o

# target to build an object file
src/World/World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/World/World.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/World/World.cpp.o
.PHONY : src/World/World.cpp.o

src/World/World.i: src/World/World.cpp.i
.PHONY : src/World/World.i

# target to preprocess a source file
src/World/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/World/World.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/World/World.cpp.i
.PHONY : src/World/World.cpp.i

src/World/World.s: src/World/World.cpp.s
.PHONY : src/World/World.s

# target to generate assembly for a file
src/World/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/World/World.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/World/World.cpp.s
.PHONY : src/World/World.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-client.dir/build.make CMakeFiles/rtype-client.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rtype-server.dir/build.make CMakeFiles/rtype-server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... rtype-client"
	@echo "... rtype-server"
	@echo "... sfml-audio"
	@echo "... sfml-graphics"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... sfml-window"
	@echo "... src/Entity/Entity.o"
	@echo "... src/Entity/Entity.i"
	@echo "... src/Entity/Entity.s"
	@echo "... src/Game/DevLevel.o"
	@echo "... src/Game/DevLevel.i"
	@echo "... src/Game/DevLevel.s"
	@echo "... src/System/System.o"
	@echo "... src/System/System.i"
	@echo "... src/System/System.s"
	@echo "... src/System/TestSystem.o"
	@echo "... src/System/TestSystem.i"
	@echo "... src/System/TestSystem.s"
	@echo "... src/World/World.o"
	@echo "... src/World/World.i"
	@echo "... src/World/World.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

